/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jensen_ndk12_NdkSimple */

#ifndef _Included_com_jensen_ndk12_NdkSimple
#define _Included_com_jensen_ndk12_NdkSimple
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jensen_ndk12_NdkSimple
 * Method:    getSignaturePassword
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jensen_ndk12_NdkSimple_getSignaturePassword
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
