/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_jensen_day15_Simple */

#ifndef _Included_com_jensen_day15_Simple
#define _Included_com_jensen_day15_Simple
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jensen_day15_Simple
 * Method:    sort
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_jensen_day15_Simple_sort
  (JNIEnv *, jclass, jintArray);

JNIEXPORT void JNICALL Java_com_jensen_day15_Simple_localRef
(JNIEnv*, jclass);

JNIEXPORT void JNICALL Java_com_jensen_day15_Simple_createGlobalRef
(JNIEnv*, jclass, jstring);

JNIEXPORT jstring JNICALL Java_com_jensen_day15_Simple_getGlobalRef
(JNIEnv*, jclass);

JNIEXPORT void JNICALL Java_com_jensen_day15_Simple_delGlobalRef
(JNIEnv*, jclass);


#ifdef __cplusplus
}
#endif
#endif
