/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_example_ndk_day14_Parcel */

#ifndef _Included_com_example_ndk_day14_Parcel
#define _Included_com_example_ndk_day14_Parcel
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_com_example_ndk_day14_Parcel_nativeCreate
(JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_example_ndk_day14_Parcel_nativeWriteInt
(JNIEnv *, jobject, jlong, jint);

JNIEXPORT jint JNICALL Java_com_example_ndk_day14_Parcel_nativeReadInt
(JNIEnv *, jobject, jlong);

JNIEXPORT void JNICALL Java_com_example_ndk_day14_Parcel_nativeSetDataPosition
(JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
