/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"//""引入自己工程的头文件；<>引入系统的头文件
/* Header for class com_jensen_ndk12_NdkSimple */
//用来打一个标记，c在编译的时候会把头文件复制到引入的地方，不管是重复引用还是相互引用都只会copy一次
#ifndef _Included_com_jensen_ndk12_NdkSimple //如果没有定义xxx
#define _Included_com_jensen_ndk12_NdkSimple //就定义这个xxx，走下面的代码
#ifdef __cplusplus//如果是c++，添加下面的内容
//不管是c还是c++统一使用c的编译方式，因为在c里面是不允许函数重载的，但是在c++里面可以；jni调用函数是根据函数名来的，必须是唯一的
extern "C" {
#endif
/*
 * Class:     com_jensen_ndk12_NdkSimple
 * Method:    getSignaturePassword
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jensen_ndk12_NdkSimple_getSignaturePassword
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
