/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jensen_ndk12_NdkSimple1 */

#ifndef _Included_com_jensen_ndk12_NdkSimple1
#define _Included_com_jensen_ndk12_NdkSimple1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jensen_ndk12_NdkSimple1
 * Method:    changeName
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jensen_ndk12_NdkSimple1_changeName
  (JNIEnv *, jobject);

/*
 * Class:     com_jensen_ndk12_NdkSimple1
 * Method:    changeInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jensen_ndk12_NdkSimple1_changeInt
  (JNIEnv *, jclass);

/*
 * Class:     com_jensen_ndk12_NdkSimple1
 * Method:    getJavaUUID
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jensen_ndk12_NdkSimple1_getJavaUUID
  (JNIEnv *, jclass);

/*
 * Class:     com_jensen_ndk12_NdkSimple1
 * Method:    createPerson
 * Signature: ()Lcom/jensen/ndk12/Person;
 */
JNIEXPORT jobject JNICALL Java_com_jensen_ndk12_NdkSimple1_createPerson
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
